### ISSUE TITLE
Insecure RNG used

### ISSUE THREAD

**Issue by BugFreeSoftware** [cordellcp3/IOTA#2]
Please make sure to use a cryptographivally secure random number generator.
From the System.Random docs:
To generate a cryptographically secure random number, such as one that's suitable for creating a random password, use the RNGCryptoServiceProvider class or derive a class from System.Security.Cryptography.RandomNumberGenerator.

**Comment by cordellcp3** [comment]
Same issue like the previous one, already answered.
